-- ============================================================================
-- Mateus Workspace — registro de acessos (IP, aparelho, página)
-- ============================================================================
-- Cole este arquivo inteiro no SQL Editor do Supabase e clique em "Run".
-- Pode rodar mais de uma vez sem problema: tudo aqui é idempotente.
--
-- Por quê: guardar uma linha por acesso ao site — de onde veio (IP), em que
-- aparelho/navegador (user-agent) e em que página — pra você poder olhar
-- depois quem acessou, sem precisar de nada em tempo real.
--
-- Depende do ajuste-02 (chave_do_chamador e aplica_limite já precisam
-- existir): é de lá que vem o IP e o limite de chamadas por aparelho.
--
-- Como ver os acessos depois: painel do Supabase → Table Editor → acessos
-- (mais recente primeiro é só clicar em "criado_em" pra ordenar decrescente).

create table if not exists public.acessos (
  id         bigint generated by default as identity primary key,
  ip         text,
  agente     text,
  pagina     text,
  usuario_id uuid references auth.users(id) on delete set null,
  criado_em  timestamptz not null default now()
);

-- RLS ligado e SEM NENHUMA política: ninguém lê nem escreve nesta tabela
-- direto pelo PostgREST, nem com a chave pública. Só a função abaixo grava
-- (roda como dona da tabela, ignora RLS) e só você lê, pelo painel.
alter table public.acessos enable row level security;

-- Função que o site chama a cada carregamento de página. security definer
-- pra conseguir gravar apesar do RLS acima; nunca estoura erro pra quem
-- chamou — registrar acesso é estatística, não pode derrubar o app se o
-- banco estiver fora ou o limite bater.
create or replace function public.registra_acesso(p_pagina text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ip     text;
  v_agente text;
begin
  -- até 20 registros por minuto por aparelho: sobra pra uso normal (cada
  -- carregamento de página é uma chamada só) e corta quem tentasse encher
  -- a tabela de propósito.
  perform public.aplica_limite('registra_acesso:' || public.chave_do_chamador(), 20, 60);

  v_ip := public.chave_do_chamador();
  v_agente := nullif(current_setting('request.headers', true)::json->>'user-agent', '');

  insert into public.acessos (ip, agente, pagina, usuario_id)
  values (v_ip, v_agente, left(coalesce(p_pagina, ''), 300), auth.uid());
exception when others then
  -- inclui o 'muitas-tentativas' do aplica_limite: nesse caso o acesso
  -- simplesmente não é registrado, sem erro nenhum voltando pro site.
  null;
end;
$$;

revoke all on function public.registra_acesso(text) from public;
grant execute on function public.registra_acesso(text) to anon, authenticated;
